[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "https://api.tvmaze.com/singlesearch/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
